baseURL: "https://rozqa.github.io/"
languageCode: en-us
title: RozQA
paginate: 10
theme: [hugo-PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: About
          url: about
          weight: -1
        - name: Archive
          url: archives
          weight: 2
        - name: Search
          url: search/
          weight: 3
        - name: Tags
          url: tags/
          weight: 1

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: RozQA
  description: "Efficient software testing and passion to quality"
  keywords: [Blog, Efficient, Software, Testing, Software Testing, Quality Assurance, Quality]
  author: 'RozQA'
  copyright: "©RozQA"

  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  disableSpecial1stPost: false
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: false
  TocOpen: true
  EnableInstantClick: true
  comments: true
  ShowAuthor: false

  # Logo and name shown on top left of site
  logo:
    text: "RozQA"
    icon: /logo.png
    iconHeight: 30

  # favicon 
  assets: 
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    appleTouchIcon: "/apple-touch-icon.png"
    safariPinnedTab: "/safari-pinned-tab.svg"

  homeInfoParams:
    Title: Wojciech Rózga - RozQA
    subtitle: efficient software testing and passion to quality
    Content: Hello there! I'm Wojciech Rózga and as a Test Architect, I’m all about boosting quality and effectiveness in software development. Here, you'll uncover my insights on quality assurance, software development, and test automation.
     <br><br>Thanks for stopping by and happy reading!
    imageUrl: 'images/avatar.webp'
    imageTitle: It's me
    imageWidth: 250
    imageHeight: 250

  socialIcons:
    - name: twitter-simple
      title: Check my X/Twitter
      url: "https://twitter.com/_rozQA"
    #- name: instagram
     # title: Check my instagram
      #url: "https://www.instagram.com/wojrozg/"
    - name: linkedin
      title: My Linkedin profile
      url: "https://www.linkedin.com/in/wojciech-rozga/"
    - name: email
      title: Drop me an email
      url: "mailto:w.rozqa@gmail.com"
    - name: github-simple
      title: View Source on Github
      url: "https://github.com/rozQA/rozQA.github.io"   

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc" 
  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.3
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true